version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: dashboard_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: dashboard_mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  redis:
    image: redis:7
    container_name: dashboard_redis
    ports:
      - "6379:6379"
    command: ["redis-server"]
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
